BOARD_SIZE = 4
MINE_VAL = float('inf')

MINE_LOCATIONS = [(0, 0), (1, 2)]  # , (2, 1)]
NUM_MINES = len(MINE_LOCATIONS)

WINDOW_HEIGHT = 400
WINDOW_WIDTH = 400
TITLE_FONT = ("Arial", 30)
TILE_FONT = ("Arial", 40)
BOARD_COLOR = '#776e65'

TILE_WIDTH = 4
TILE_HEIGHT = 2
TILE_PADX = 5
TILE_PADY = 5

TILE_COLOR = '#BDAD9E'